services:
  # -----------------------
  # Postgres (Shared)
  # -----------------------
  postgres:
    image: postgres:15
    container_name: postgres_main
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: metastore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      # - my-network
      - data-platform
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d metastore_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # -----------------------
  # Nessie Catalog
  # -----------------------
  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: nessie_catalog
    environment:
      NESSIE_VERSION_STORE_TYPE: JDBC2
      NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE: postgresql
      QUARKUS_DATASOURCE_POSTGRESQL_JDBC_URL: jdbc:postgresql://postgres:5432/metastore_db
      QUARKUS_DATASOURCE_POSTGRESQL_USERNAME: admin
      QUARKUS_DATASOURCE_POSTGRESQL_PASSWORD: admin
    ports:
      - "19120:19120"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      # - my-network
      - data-platform

  # -----------------------
  # Superset
  # -----------------------
  superset:
    build: ./superset
    container_name: superset
    # env_file:
    #   - .env
    ports:
      - "8088:8088"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@admin.com
      SECRET_KEY: supersecretkey123
      # MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://admin:admin@postgres:5432/superset
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - superset_home:/app/superset_home
    networks:
      # - my-network
      - data-platform

  # -----------------------
  # MinIO
  # -----------------------
  minio:
    image: minio/minio
    container_name: minio_iceberg
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/minio-data
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set myminio http://localhost:9000 admin password;
      mc mb myminio/lakehouse;
      tail -f /dev/null"
    networks:
      # - my-network
      - data-platform

  # -----------------------
  # Trino
  # -----------------------
  controller:
    image: trinodb/trino
    container_name: trino-controller
    hostname: trino
    mem_limit: 4g
    volumes:
      - ./trino/catalog:/etc/trino/catalog
    ports:
      - "9080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      # - my-network
      - data-platform

volumes:
  postgres_data:
  superset_home:

networks:
  # my-network:
  data-platform:
    external: true
